allowBuilds:
  '@prisma/engines': false
  esbuild: false
  prisma: false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
